### ISSUE TITLE
Make pythonOverrides composable?

### ISSUE THREAD

**Issue by mikepurvis** [lopsided98/nix-ros-overlay#118]
I'm hitting an issue where I want to further override some of the nix-ros-overlay python packages in my own flake, and I'd like to do so in a way that doesn't have me vendoring out the whole thing, but this seems to requires some cooperation between the overlays, per:

https://discourse.nixos.org/t/makeextensibleasoverlay/7116/5

Would we consider this?

**Comment by mikepurvis** [comment]
Based on the discussion in https://github.com/NixOS/nixpkgs/issues/44426#issuecomment-532208394; we might be able to get python composability for free if this were changed to overrideScope':

https://github.com/lopsided98/nix-ros-overlay/blob/e90355503d47d9a6a5907673bb5c1939fa124d7d/pkgs/default.nix#L3-L4

Will experiment and send a PR if something comes of it.

**Comment by lopsided98** [comment]
I don't think the PR that made that work was merged.

**Comment by mikepurvis** [comment]
Oh, so I see. :(

I've been using `overrideScope'` at the top level and it seems to work really well for me; that's too bad it never made it in for `pythonPackages`.

**Comment by lopsided98** [comment]
I implemented the alternative technique in the linked Discourse thread.
