### ISSUE TITLE
Turtlebot shell fails to build due to gazebo

### ISSUE THREAD

**Issue by wcole3** [lopsided98/nix-ros-overlay#199]
The shell in the example script fails to build with the errors resulting from compiling at c++ 14 standard.  By pulling down the repo and manually adding `cmakeFlags = [ "-DCMAKE_CXX_STANDARD=17" ];` to the default.nix files in distros/noetic/gazebo-plugins and distros/noetic/gazebo-ros allows the command `nix-shell examples/turtlebot3-gazebo.nix` to correctly build the shell.  

Launching turtlebot works as expects from that shell.  Not sure how to address this, but we have be able to reproduce this on a few different machines.

**Comment by TilCreator** [comment]
Can reproduce, the fix also works! Can you please open a PR for this?

**Comment by lopsided98** [comment]
Updating Gazebo and its dependencies fixed this.
