### ISSUE TITLE
Adding Python module packages

### ISSUE THREAD

**Issue by hacker1024** [lopsided98/nix-ros-overlay#231]
One of my ROS packages requires Tkinter. Is there a way to add packages such as these to the Python environment used by ROS?

**Comment by lopsided98** [comment]
Yes, it should mostly work the same as anything else in Nix. What have you tried?

**Comment by hacker1024** [comment]
Well, normally if I want to add packages to a Python derivation, I'd use the `withPackages` function. It's not clear to me how to modify the Python derivation used by ROS, however. Does it just use a Python derivation from Nixpkgs? If so, an overlay can be used, but for which version?

**Comment by lopsided98** [comment]
Yeah, `withPackages` expects you to run to only run the Python binary in the environment it returns, which won't work with ROS. I normally just add Python packages directly to the shell `buildInputs` or the ROS `buildEnv`, without using `withPackages`.

**Comment by hacker1024** [comment]
Thanks, that works well.
