### ISSUE TITLE
How rosdistro keys are resolves in overlay?

### ISSUE THREAD

**Issue by movefasta** [lopsided98/nix-ros-overlay#237]
Hi!
I would like to build new Gazebo Garden (ex-Ignition Gazebo) in nix and need some advices from more experienced users.

rosdistro contain records/keys for OS-related packages, where nixos packages included too. I see, for example, package `ignition-math6: nixos: [ignition.math6]`. nix-file in overlay https://github.com/lopsided98/nix-ros-overlay/blob/master/pkgs/ignition/math/default.nix consist pname `"ignition-math${majorVersion}";`, but in [rosdistro](https://github.com/ros/rosdistro/blob/9cfaef7339b94ee28daa8ed1af69be870a37ab0d/rosdep/base.yaml#L2074) it named as `ignition.math6`. How name `ignition.math6` in rosdistro resolves to `ignition-math6`?

**Comment by lopsided98** [comment]
In Nix, the `pname` attribute does not necessarily match the attribute name for the package in the package set. `pname` is only used to form the Nix store path name. The package set is defined here: https://github.com/lopsided98/nix-ros-overlay/blob/master/pkgs/default.nix#L80
