### ISSUE TITLE
Broken package definition due to quote in package metadata

### ISSUE THREAD

**Issue by koalp** [lopsided98/nix-ros-overlay#356]
In [the sick_scan_xd package](https://github.com/SICKAG/sick_scan_xd/blob/develop/package.xml), there are quote in the license definition.

it results in a broken license definition in the corresponding nix package : 

https://github.com/lopsided98/nix-ros-overlay/blob/9f53d85d2a20447f67048a85e5e79e8753dce327/distros/humble/sick-scan-xd/default.nix#L22-L25

It may be an issue for any package with quote in metadata but I haven't found another one yet. 

What would be the best way to solve the issue ? Open a PR in sick_scan_xd or modify `superflore-gen-nix` to strip quotes ?

**Comment by lopsided98** [comment]
The correct solution is to make superflore escape quotes properly.
