### ISSUE TITLE
ros-env fails to evaluate: empy_3 no longer exists

### ISSUE THREAD

**Issue by kjeremy** [lopsided98/nix-ros-overlay#379]
https://github.com/lopsided98/nix-ros-overlay/blob/1b9585ae8f529b2b392203f2dda6fb96311621a9/distros/distro-overlay.nix#L9 is causing me some trouble.

I get a `error: attribute 'empy_3' missing`

**Comment by wentasah** [comment]
Which command/Nix expression are you trying to run/evaluate? My projects based on humble work fine even with the latest `develop` branch.

**Comment by kjeremy** [comment]
I think this is a local issue

**Comment by kjeremy** [comment]
Okay I think I'm overriding python incorrectly. If I add the following to an overlay then I get the error about `empy_3`. This worked a long time ago so maybe there's a different way to override python now?

```nix
python3 = super.python3.override {};
```
