### ISSUE TITLE
Example broken due to nixpkgs breakage on bcrypt.

### ISSUE THREAD

**Issue by breakds** [lopsided98/nix-ros-overlay#49]
Just to report that currently the example will fail because of the breakage in `nixpkgs`:

https://github.com/NixOS/nixpkgs/pull/97996

I think this is because the default `nixpkgs` used here is a fork which does not have this fix yet. Can you merge the new commits from upstream when you have time?

Thanks!

**Comment by lopsided98** [comment]
Interesting, I saw that breakage (but forgot about the example) and assumed that Python 2 support was just going to be dropped permanently. Anyway, I updated the fork.

**Comment by breakds** [comment]
Thanks!
