### ISSUE TITLE
The gazebo patch cannot be downloaded

### ISSUE THREAD

**Issue by breakds** [lopsided98/nix-ros-overlay#50]
The reference to the gazbo patch is here:

https://github.com/lopsided98/nix-ros-overlay/blob/77c2aca4c4dbbdbe55844f760e653dad632be683/pkgs/gazebo/7.nix#L20

It seems that the repo is gone. Do you happen to still have the patch somewhere? What is the patch about?

Thanks!

**Comment by lopsided98** [comment]
I deleted the repo the PR was merged upstream. I've updated the patches to point at the upstream repo.
