### ISSUE TITLE
Consider moving to newer `buildPythonPackage`

### ISSUE THREAD

**Issue by kjeremy** [lopsided98/nix-ros-overlay#507]
Lately I've been running into a number of noetic packages missing `distutils` (see #506).

I don't really know how python is done these days but I've solved a similar issue with `lcov-cobertura` (NixOS/nixpkgs#349333) at runtime by converting to the `pyproject`, `build-system` and `dependencies` attributes.

See: https://nixos.org/manual/nixpkgs/unstable/#buildpythonpackage-parameters

**Comment by lopsided98** [comment]
Doesn't that require the upstream project to have a `pyproject.toml` file?. Also, the reason your PR fixed `lcov-cobertura` is because you explicitly added `distutils` as a dependency, not because you converted it to pyproject.
