### ISSUE TITLE
freeimage is marked as insecure

### ISSUE THREAD

**Issue by Jack17432** [lopsided98/nix-ros-overlay#515]
I have tryed to enter the dev shell with the basic command

`nix develop github:lopsided98/nix-ros-overlay#example-turtlebot3-gazebo`

However I get the following error

`error: Package ‘freeimage-unstable-2021-11-01’ in /nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source/pkgs/development/libraries/freeimage/default.nix:72 is marked as insecure, refusing to evaluate.`

My whole nixos flake is in my .dotfiles repo if you need to see full system

**Comment by lopsided98** [comment]
Yes, freeimage is abandoned and has unpatched CVEs, yet gazebo still requires it. To use it anyway, follow the instructions printed in the error.
