### ISSUE TITLE
How do I set up environment variables like $ROS_PACKAGE_PATH

### ISSUE THREAD

**Issue by werner291** [lopsided98/nix-ros-overlay#74]
Hello,

this tutorial (http://wiki.ros.org/catkin/Tutorials/create_a_workspace) instructs me to `source /opt/ros/noetic/setup.bash`. Where can I find `setup.bash` when applying the overlay?

`echo $ROS_PACKAGE_PATH` just outpus an empty line.

Here's the shell.nix that I use:

[shell.nix](https://github.com/lopsided98/nix-ros-overlay/files/5843014/shell.nix.txt)

**Comment by lopsided98** [comment]
You don't need to (in fact you can't) source `setup.bash` with this overlay unless you are developing with a catkin workspace, in which case you would source `devel/setup.bash` from within the workspace.

The `ros-environment` package sets up those environment variables. It should be pulled in automatically if you add any other ROS package to the environment, but catkin itself doesn't depend on it.
