### ISSUE TITLE
urdf_tutorial appears to have some dependency issues

### ISSUE THREAD

**Issue by werner291** [lopsided98/nix-ros-overlay#84]
Hello again,

the package urdf_tutorial in noetic appears to be missing a dependency to `xacro`, and the path to `urdf_tutorial` appears to be missing from `ROS_PACKAGE_PATH, when installed into a nix shell.

I'll probably just be using rviz directly instead, but I figured I'd let you know.

**Comment by lopsided98** [comment]
I can't reproduce this either. `urdf_tutorial` has `xacro` as a dependency, see: https://github.com/lopsided98/nix-ros-overlay/blob/master/distros/noetic/urdf-tutorial/default.nix#L18, and it is correctly added to `ROS_PACKAGE_PATH` when I added it to a shell.
