### ISSUE TITLE
aarch64 cache

### ISSUE THREAD

**Issue by 3noch** [lopsided98/nix-ros-overlay#93]
I've discovered that setting up an aarch64 cache with GitHub actions and Cachix is actually really easy.

You need
```
uses: docker/setup-qemu-action@v1
```

and then run your build with

```
nix-build --option system aarch64-linux --extra-platforms aarch64-linux
```

**Comment by lopsided98** [comment]
I've been trying this out, and it works but tends to timeout with mass-rebuilds.

**Comment by 3noch** [comment]
@lopsided98 Does that pose a real problem? Since cachix keeps all intermediate builds, you just need to start the build again to keep going. You also have the option of building it locally (perhaps via qemu binfmt support in NixOS) and then pushing to the cache to fill it.

**Comment by 3noch** [comment]
But you're absolutely right that binfmt approach is extremely slow. I have an aarch64 device that is *slightly* faster but unimpressively so.

**Comment by lopsided98** [comment]
Yeah, it hasn't been too much of a problem over the last month I've been running it.
